### ISSUE TITLE
Start Scene doesn't work

### ISSUE THREAD

**Issue by sambickley** [balaam/tiny_rogue#82]
The buttons in the Start Scene both have scripts to load into either the ASCII or Graphical version of Tiny Rogue.. unfortunately they don't work, and instead throw the following error:

```
EntityManager.AddComponent/RemoveComponent/CreateEntity/DestroyEntity are not allowed during Entities.ForEach. Please use PostUpdateCommandBuffer to delay applying those changes until after ForEach.
   at Unity.Entities.EntityManager.BeforeStructuralChange() in C:\UnityDev\hw19-tiny_rogue\Library\PackageCache\com.unity.entities@0.0.12-preview.33\Unity.Entities\EntityManagerSync.cs:line 33
   at Unity.Entities.EntityManager.CreateEntity() in C:\UnityDev\hw19-tiny_rogue\Library\PackageCache\com.unity.entities@0.0.12-preview.33\Unity.Entities\EntityManagerCreateDestroyEntities.cs:line 57
   at Unity.Tiny.Scenes.SceneService.LoadSceneAsync(SceneGuid sceneGuid) in C:\UnityDev\hw19-tiny_rogue\Library\PackageCache\com.unity.tiny@0.15.3-preview\DotsModules\Unity.Tiny.Scenes\SceneStreamingSystem.cs:line 69
   at ButtonLoadSceneSystem.<OnUpdate>b__0_0(Entity entity, PointerInteraction& pointerInteraction) in C:\UnityDev\hw19-tiny_rogue\Assets\tiny_rogue\Scripts\Systems\UI\ButtonLoadSceneSystem.cs:line 15
   at Unity.Entities.EntityQueryBuilder.ForEach[T0](F_ED`1 action) in C:\UnityDev\hw19-tiny_rogue\Library\PackageCache\com.unity.entities@0.0.12-preview.33\Unity.Entities\EntityQueryBuilder_ForEach.gen.cs:line 82
   at ButtonLoadSceneSystem.OnUpdate() in C:\UnityDev\hw19-tiny_rogue\Assets\tiny_rogue\Scripts\Systems\UI\ButtonLoadSceneSystem.cs:line 13
   at Unity.Entities.ComponentSystem.InternalUpdate() in C:\UnityDev\hw19-tiny_rogue\Library\PackageCache\com.unity.entities@0.0.12-preview.33\Unity.Entities\ComponentSystem.cs:line 818
   at Unity.Entities.ComponentSystemGroup.OnUpdate() in C:\UnityDev\hw19-tiny_rogue\Library\PackageCache\com.unity.entities@0.0.12-preview.33\Unity.Entities\ComponentSystemGroup.cs:line 451
```

I think this can be fixed by pushing the call to `LoadSceneAsync` in ButtonLoadSceneSystem.cs out to a command buffer.. but I'm not technically knowledgeable enough to investigate/implement this myself.

**Comment by sambickley** [comment]
Fixed by Marc.
